### ISSUE TITLE
کار نکردن 

### ISSUE THREAD

**Issue by alizadeh8022** [SourceSara/Compiler#1]
![Screenshot_۲۰۲۳۰۶۳۰_۲۳۴۳۵۶_Chrome](https://github.com/SourceSara/Compiler/assets/136198728/0f53bcde-b9e9-4779-8eb0-de8ffa7fc9d3)

Why does this warn?

**Comment by AmRo045** [comment]
سلام
دستور دوم رو نمیتونید داخل کامپایلر آنلاین اجرا کنید و باید داخل ترمینال سیستمی که بهش دسترسی دارین اجرا کنید.

**Comment by Samiyarr** [comment]
چرا
